### ISSUE TITLE
Wait for multi-threaded decomp

### ISSUE THREAD

**Issue by Artoria2e5** [AOSC-Dev/aoscdk-rs#10]
xz2 might be receiving multi-threaded decompression soon: https://github.com/alexcrichton/xz2-rs/issues/113. When that lands we would get much better install performance, maybe finally enough to saturate a hard drive's write speed.

(It does require a properly-compressed tarball though. Are they compressed with threads?)

**Comment by MingcongBai** [comment]
@Artoria2e5 Yes, compressed with xz -T0.

**Comment by eatradish** [comment]
aoscdk-rs now support squashfs multi thread decompress, closing ...
