### ISSUE TITLE
Deploykit doesn't support ppc64el architecture

### ISSUE THREAD

**Issue by CamberLoid** [AOSC-Dev/aoscdk-rs#5]
aoscdk-rs reports `Unsupported architecture` when executing in qemu-emulated ppc64le pseries environment. 

![image](https://user-images.githubusercontent.com/22998116/164985373-3db92b5c-a777-4f46-b2ad-432b3c68f955.png)

---

Well this may be because rust cannot tell the difference between ppc64 and ppc64el/le (std::env::consts::ARCH are both `powerpc64` !). A possible fix is adding `"powerpc64" => Some("ppc64el")` in get_arch_name() from https://github.com/AOSC-Dev/aoscdk-rs/blame/master/src/network.rs

**Comment by eatradish** [comment]
deploykit does not support ppc64el, because we cannot guarantee bootloader writes.

**Comment by eatradish** [comment]
Currently aoscdk-rs (master branch) already supports the installation of ppc64el, request a test.

**Comment by MingcongBai** [comment]
This is already fixed. Closing.
